language: php

sudo: false

env:
  global:
    - secure: "n2DDk9sHbG/gYYVA/kPXZLa4Tgcy1HFV4JuBEMkVzQ6U/i178jA+pxG8eg9rTfIfTvmFXnbyURJH0aKeFvXd2kpnOzPwY/+DwY0gvJZGFlkEstpAVz4djMeXkltaYMzjKzKIk7uTwFRPPHG3/+L82eWJ8InaMp9OwfPTTsWOYgzoig3ZGzkUX7+vKxCh8zz8A5Hjp0b/kI0gPR7hYRfsYZ04u15UkTFjvq68ce730lHWHjYEVcQHTfdymDsXuHLKR2640TpXWBKGi5L6228cturj5MhA92zQZJ3xdFEFC2omXGB3++R9Qlk5zMlhVNylFqtbuCmUiKzAllQMRUPv7ueUGj5f/ENegNP0/RHz5XPzKNehPKkeCEQa6kuUt1l5p6S6oMk33yEEoGsGK541ID6Tctd1MPHjm/q+knP563SPHqRmZR07bOhdurwuc4DZIhFgnerzlAPfUPGugmm7YG8t0l0nwFNgZnQ9m2kNA8yi30NCk+Z81PTju7Nn0gSKLsnw7OZjebg5vKvuwjJnDpj0s84iT20KXIsn7EsvuzTABiPcH3nfOXxBROi67DHaoiWQJSeCO6+LXrolPUsMX7QjAZtCwalXFdVs+f+iTa0SmjcdQ8Cbfu7VPn+ZNyHakfdctt5bbjoVwRwLq7gCoBHHUmliLQc3X6hTM56/wXw="

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer install --prefer-dist

script:
  - vendor/bin/phpunit

after_script:
  - travis_retry php vendor/bin/coveralls -v

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_PHP_VERSION = "7.0" && bash ./scripts/api.sh

cache:
  directories:
    - $HOME/.composer/cache
